### ISSUE TITLE
Log out problem

### ISSUE THREAD

**Issue by 0CreepySmile0** [KikyoBRV/ku-polls#52]
App log user out and instantly redirects user to login page which force visitor to click browser's "go back" button which make the latest page not update and lead to server error when try clicking "Log out" again

**Comment by KikyoBRV** [comment]
I'm adding a 'Continue as Guest' button to the login and sign-up pages to prevent this problem from occurring. I am also modifying the logout behavior on all pages so that it does not redirect to the login page when the user clicks it. This change will prevent users from having to go back to the previous URL, thereby avoiding the issue.
